version: '3.4'

services:
  vivalliuswebb-api:
    image: ${DOCKER_REGISTRY-}vivalliuswebbapi
    build:
      context: .
      dockerfile: VivalliusWebb-API/Dockerfile
    ports:
      - 4980:80
      - 4981:443
    environment:
      - "Development"
    networks:
      - internal

  vivalliusSql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: vivallius
      MYSQL_USER: admin
      MYSQL_PASSWORD: sksa
      MYSQL_ROOT_PASSWORD: sksa1955-12-05
    volumes:
      - "vivalliusStorage:/var/lib/mysql"
    restart: always
    ports:
      - 4982:3306
    networks:
      - internal

volumes:
  vivalliusStorage:

networks:
  internal:
