version: '3.4'

services:
  vivalliuswebb-api:
    image: ${DOCKER_REGISTRY-}vivalliuswebbapi
    build:
      context: .
      dockerfile: VivalliusWebb-API/Dockerfile
    ports:
        - 4811:80
    environment:
        - "Development"
  vivalliusSql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "vivallius"
      MYSQL_USER: "Admin"
      MYSQL_PASSWORD: "sksa"
      MYSQL_ROOT_PASSWORD: "sksa1955-12-05"
    volumes:
        - "vivalliusStorage:/var/lib/mysql"
    restart: always
    ports:
        - 4810:3301
volumes:
  vivalliusStorage:
networks:
  internal: